### ISSUE TITLE
Site Structure Not (yet) Available

### ISSUE THREAD

**Issue by israelzuniga** [ColimaHacklab/wiki#1]
Based on the actual content, we should create something like this:
hacklab.cc/ 
    |
    |»> Nosotros.md
    |»> Equipamiento.md
    |»> Blog/ (blogging app)
    |»> Calendario (Cal app)
    |»> Membresia.md
    |»> Contacto.md

**Comment by jescarri** [comment]
Initial revision can be found here:
[[https://github.com/ColimaHacklab/wiki/pull/3 Pull Request]]
